#cloud-config
packages:
- strace
- tcpdump
- bind-utils
- tmux
- git
- python3-virtualenv
- pdsh
- pdsh-rcmd-ssh
- pdsh-mod-genders
runcmd:
- echo 'setw -g mouse' > /etc/tmux.conf
- test -f /root/.ssh/id_rsa||ssh-keygen -t rsa -b 4096 -N "" -f /root/.ssh/id_rsa
users:
- name: ${user}
  shell: /bin/bash
  sudo: ALL=(ALL) NOPASSWD:ALL
  ssh_authorized_keys:
  - ${sshkey}
